config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "game#index"
  get "/end", to: "game#end"
  get "/rank", to: "game#rank"

  resources :questions, only: [:show] do
    post "/close", to: "questions#close"
  end
  
  resources :user, only: [:show] do
    collection do
      post "/answer", to: "user#answer"
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :users, through: :answers
end

app/models/setting.rb
class Setting < ApplicationRecord
  enum :status, [ :open, :closed ], suffix: true, default: :open

  after_update_commit -> {
    broadcast_replace_to "setting_#{self.id}", partial: "user/form", locals: {question: self}, target: "setting_#{self.id}"
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :answers, dependent: :destroy
  has_many :questions, through: :answers

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def answer_score_sum
    self.answers.sum(:score)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || user_path(resource.id)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def layout_by_resource
    if devise_controller?
      "user"
    else
      "application"
    end
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.email != "info@bssc.vn"
      redirect_to user_path(current_user.id)
    end

    question_step = Setting.first
    question_step.update(value: 0)

    qrcode = RQRCode::QRCode.new(new_user_session_url)
    @qr_svg = qrcode.as_svg(fill: "000", color: "FFF", shape_rendering: "crispEdges", module_size: 10, standalone: true, use_path: true)
  end

  def end
  end

  def rank
    @users = User.where.not(email: "info@bssc.vn").sort_by(&:answer_score_sum).reverse!
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :close]
  skip_before_action :verify_authenticity_token, only: [:close]

  def show
    if current_user.email != "info@bssc.vn"
      redirect_to user_path(current_user.id)
    end

    question_step = Setting.first
    question_step.update(value: @question.id, status: "open")
  
    @answers = @question.answers.order(created_at: :desc)

    if Question.where("id > ?", @question.id).first.present?
      @next_question = question_path(Question.where("id > ?", @question.id).first)
    else
      @next_question = end_path
    end
  end

  def close
    question_step = Setting.first
    question_step.update(status: "closed")
  end

  private

  def set_question
    @question = Question.find(params[:id] || params[:question_id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  layout "user"

  before_action :authenticate_user!

  def show
    @question = Setting.first
  end

  def answer
    if current_user.answers.find_by_content(params[:content]).blank?
      question = Question.find(params[:question_id])
      if question.related_words.any?{ |s| s.gsub(/[^0-9A-Za-z]/, "").delete(" ").singularize.casecmp( params[:content].gsub(/[^0-9A-Za-z]/, "").delete(" ").singularize ) === 0 }
        score = 1
      else
        score = 0
      end

      answer = current_user.answers.build(content: params[:content], question_id: params[:question_id], score: score)
      if answer.save
        redirect_to user_path(current_user), notice: "Keyword was successfully submitted"
      else
        redirect_to user_path(current_user), alert: "Error: keyword was not submitted"
      end
    else
      redirect_to user_path(current_user), alert: "You have already submitted this keyword"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/end.html.erb
<div class="pt-36 z-10 relative">
  <div class="flex flex-col items-center gap-12">
    <div class="flex flex-col gap-4 justify-center items-center">
      <h1 class="text-6xl text-white">Thank you for joining VICAP 2022</h1>
      <%= link_to "Ranking", rank_path, class: "w-36 rounded text-center text-lg text-white bg-pink-600 hover:bg-pink-700 px-12 py-3 uppercase" %>
    </div>
  </div>
</div>

app/views/game/index.html.erb
<div class="pt-12">
  <div class="flex flex-col items-center gap-12">
    <div class="flex flex-col gap-4">
      <h1 class="text-4xl text-white">VICAP 2022</h1>
      <%= link_to "Game On", question_path(Question.first.id), class: "rounded text-center text-lg text-white bg-pink-600 hover:bg-pink-700 px-12 py-3 uppercase" %>
    </div>

    <div class="text-center">
      <h3 class="text-white font-bold">Scan QR Code to start</h3>
      <div class="rounded mt-2 border-4 border-pink-600 shadow-xl shadow-pink-500/50 bg-transparent z-10 relative p-4">
        <%= render inline: @qr_svg %>
      </div>
    </div>
  </div>
</div>

<audio class="fixed z-10 bottom-2 left-0" controls>
  <source src="/intro.mp3" type="audio/mp3">
</audio>

app/views/game/rank.html.erb
<div class="py-12 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-full overflow-y-auto relative z-10">
  <div class="">
    <h1 class="text-9xl text-white">Ranking</h1>
  </div>>
  
  <div class="flex items-center justify-between">
    <div class="">
      <span class="text-pink-600 text-8xl">Attendee</span>
    </div>

    <div>
      <span class="text-pink-600 text-8xl">Score</span>
    </div>
  </div>

  <% @users.each do |user| %>
    <div class="flex items-center justify-between">
      <div class="">
        <span class="text-white text-6xl"><%= user.username %></span>
      </div>

      <div>
        <span class="text-white text-6xl"><%= user.answers.sum(:score) %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vicap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="audio" class="bg-gray-900 bg-gradient-custom">
    <main class="flex h-full items-center justify-center">
      <div class="w-full h-full absolute mx-auto perspective">
        <div class="landscape"></div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vicap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body class="text-lg">
    <header class="fixed top-0 left-0 h-16 w-full flex items-center justify-center">
      <h1 class="text-2xl text-pink-600 text-center">
        VICAP 2022
        <% if user_signed_in? %>
        - ID <%= current_user.username %>
        <% end %>
      </h1>
    </header>

    <main class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_answer.html.erb
<div id="<%= dom_id(answer) %>" class="bg-white px-3 w-28 h-12 flex flex-col items-center justify-center rounded-full text-center">
  <span class="text-pink-600"><%= answer.content %></span>
</div>

app/views/questions/show.html.erb
<%= turbo_stream_from "answers" %>

<div class="pt-12 z-10 relative">
  <div class="flex flex-col items-center justify-center">
    <div id="question" class="relative group transform-gpu transition ease-in-out duration-200">
      <div class="absolute -inset-2 bg-gradient-to-r from-pink-600 to-purple-600 rounded-lg blur opacity-75 group-hover:opacity-100 transition duration-1000 group-hover:duration-200 animate-tilt"></div>
        <button class="relative px-7 py-4 bg-black rounded-lg leading-none flex items-center divide-x divide-gray-600">
          <h1 class="text-white text-8xl text-center relative">
            <%= @question.word %>
          </h1>
        </button>
      </div>
    </div>
    
    <div
      data-controller="countdown"
      data-countdown-endtime-value="<%= (Time.now + 31.seconds).rfc2822 %>"
      data-countdown-next-value="<%= @next_question %>"
      class="mt-6 text-8xl text-white font-bold text-center"
    >
      30
    </div>
  </div>

  <div id="results" class="hidden">
    <div class="relative z-10 flex flex-wrap items-center justify-center gap-6">
      <% @question.related_words.first(10).each do |word| %>
        <div class="inline-flex items-center justify-center w-44 h-44 rounded-full border-2 border-pink-600 bg-pink-600">
          <span class="text-white text-4xl text-center"><%= word %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

<audio autoplay>
  <source src="/intro.mp3" type="audio/mp3">
</audio>

app/views/user/_form.html.erb
<div id="<%= dom_id(question) %>" class="mt-8">
  <% if question.value.to_i > 0 && question.status == "open" %>
    <%= form_with(url: answer_user_index_path) do |f| %>
      <div class="flex flex-col gap-1">
        <h3 class="text-center text-xl">Enter your keyword for</h3>
        <div class="w-56 h-12 bg-gray-200 text-center flex items-center justify-center mx-auto">
          <%= Question.find(question.value.to_i).word %>
        </div>
      </div>

      <div class="mt-8 flex flex-col gap-1">
        <%= f.text_field :content, autofocus: true, autocomplete: "off" %>
        <%= f.hidden_field :question_id, value: Question.find(question.value.to_i).id %>
      </div>

      <div class="mt-4">
        <%= f.submit "Submit", class: 'cursor-pointer w-full bg-blue-600 text-white px-2 py-3 hover:bg-blue-700' %>
      </div>
    <% end %>
  <% elsif question.status == "closed" %>
    <p class="text-center">This question has been closed</p>
  <% else %>
    <p class="text-center">Game hasn't started. Wait a moment...</p>
  <% end %>
</div>

app/views/user/show.html.erb
<%= turbo_stream_from "setting_1" %>

<div class="sm:mx-auto sm:w-full sm:max-w-md px-4">
  <%= render "form", question: @question %>

  <% flash.each do |type, msg| %>
    <div data-controller="alert" class="text-center <%= type == 'notice' ? 'bg-green-200' : 'bg-red-200' %> px-2 py-1 mt-2">
      <%= msg %>
    </div>
  <% end %>
</div>